# Generated by Django 3.0.3 on 2020-02-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.IntegerField(null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.User')),
                ('user_id', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('hobby', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
    ]
