FIRST_NAME_IS_INVALID = 'first name is invalid'
LAST_NAME_IS_INVALID = 'Last name is invalid'
PASSWORD_IS_INVALID = 'Password is invalid'
PHONE_IS_INVALID = 'Phone is invalid'
REGISTER_FAIL = 'Register fail'
REGISTER_SUCCESS = 'Register success'