# Generated by Django 3.0.3 on 2020-02-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.IntegerField(null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.IntegerField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.IntegerField(null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.IntegerField(null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200, null=True)),
                ('video', models.CharField(max_length=200, null=True)),
                ('suppose_num', models.IntegerField(default=0)),
                ('download_num', models.IntegerField(default=0)),
                ('main_page', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
